export const APP_DB_STATUS_INITIALIZATION = 'APP_DB_STATUS_INITIALIZATION';
export const APP_DB_STATUS_CONNECTING = 'APP_DB_STATUS_CONNECTING';
export const APP_DB_STATUS_OPEN = 'APP_DB_STATUS_OPEN';
export const APP_DB_STATUS_HAS_DATA = 'APP_DB_STATUS_HAS_DATA';
export const APP_DB_STATUS_ERROR = 'APP_DB_STATUS_ERROR';
export const APP_DB_STATUS_CLOSE = 'APP_DB_STATUS_CLOSE';